spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.0.177:3306/patent?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: bwj
    password: bwj

#mybatis的相关配置
mybatis:
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

elasticsearch:
  address: 10.1.0.177:9200
  username: elastic
  password: elastic
  key-store-pass: 6MkOuto0Q7-VqYldF_pTzw
  trust-store-class-path: security/http.p12
  http-scheme: https

flask:
  url: http://10.1.0.177:5000